version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - mongo

  mongo:
    image: mongo:6
    ports:
      - "27027:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
